name    'puppet-logstash'
version '0.3.3'
source 'https://github.com/zen/puppet-logstash'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Logstash'
description 'Module for managing and configuring Logstash'
project_page 'https://github.com/zen/puppet-logstash'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
